version: '3.8'
services:
  php_apache_server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php_apache_server
    depends_on:
      - database
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
  database:
    container_name: mysql_db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cloud_quest_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: 1234
    ports:
      - 6033:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: database
    depends_on:
      - database